### ISSUE TITLE
Setting a max bitrate on React Native Android and iOS.

### ISSUE THREAD

**Issue by YoucefBen47** [bitmovin/bitmovin-player-react-native#104]
Is there a way to limit the bitrate on React Native ? We would like to set a Max Bitrate to control the highest quality that can be played.

**Comment by rolandkakonyi** [comment]
Hi @YoucefBen47, this is currently not supported but we are happy to accept contributions!

You could implement it by adding support for `PlayerConfig.adaptationConfig` for both platforms.
