### ISSUE TITLE
Creating custom event [iOS]

### ISSUE THREAD

**Issue by Danielcomes92** [bitmovin/bitmovin-player-react-native#107]
Hi @dweinber,
We are trying to create a custom event using your SDK. 

Our current goal is to connect the custom close button to the RN App, and just for testing purposes, retrieve the "closePlayer" message when the user presses it.

![Screenshot 2023-04-11 at 15 21 19](https://user-images.githubusercontent.com/67914980/231256096-9ea1a56b-9b0a-4f41-a1f2-80aac99d662d.png)

![Simulator Screen Shot - iPhone 14 - 2023-04-11 at 15 19 15](https://user-images.githubusercontent.com/67914980/231255537-1f3526e1-14f7-4127-a2fe-b5d1292a78bf.png)

****The flow we are following to configure this is the next one;****

**We have created two new events in the react native app**

![Screenshot 2023-04-11 at 15 18 59](https://user-images.githubusercontent.com/67914980/231255712-9d004244-be66-4c51-b0c3-30e9e1ed34aa.png)

**Declared the events in RNPlayerView**

![Screenshot 2023-04-11 at 15 17 04](https://user-images.githubusercontent.com/67914980/231255890-4a1139e4-b79c-49fa-9bdb-97a00d1e5daf.png)

**We have created an extension for RNPlayerView, but at this point we are experiencing the following error**

![Screenshot 2023-04-11 at 15 16 38](https://user-images.githubusercontent.com/67914980/231256037-7ddd8233-5f8c-4e66-8434-bad1d757e504.png)

If you can help us fix the problem, we would appreciate it.

Thanks in advance,
Daniel.

**Comment by jonathanm-tkf** [comment]
Hi team @pogist @slederer @matamegger 

Could you help us with this implementation, currently we are adding in iOS but surely we need the implementation of Android in the same way, I thank you for the contribution.

Related issue https://github.com/bitmovin/bitmovin-player-react-native/issues/12

**Comment by rolandkakonyi** [comment]
Hi @Danielcomes92 and @jonathanm-tkf!
One problem I see with the error on the screenshot is that the actual signature that has to be implemented is `func receivedSynchronousMessage(_ message: String, withData data: String?) -> String?` so you are missing `-> String?` there.
Xcode is trying to help you with a suggestion on that error message.

**Comment by jonathanm-tkf** [comment]
I am not understanding your comment, could you help us with an example?

**Comment by rolandkakonyi** [comment]
@jonathanm-tkf I meant that you are on the right track but you need to adapt line 4 on the last screenshot and replace `func receivedSynchronousMessage(_ message: String, withData data: String?)` with `func receivedSynchronousMessage(_ message: String, withData data: String?) -> String?`

**Comment by jonathanm-tkf** [comment]
I understand @rolandkakonyi but basically, this does not solve the full integration, we have explained the drawback, unfortunately, we do not have all the resources to help in this complex part of the project, we would need someone to guide us in the integration, is this possible? Previously you were helping us @pogist giving us advice explanations etc, can we have some help from your side?

**Comment by jonathanm-tkf** [comment]
hello @rolandkakonyi is there anything we can do to help? we have tried to follow your steps but we keep getting the same error, just to clarify we created a PR some time ago, if you could review it and/or help us with the steps to follow it would be of great help.

**Comment by jonathanm-tkf** [comment]
https://github.com/bitmovin/bitmovin-player-react-native/pull/109

**Comment by rolandkakonyi** [comment]
This was implemented by #129
