### ISSUE TITLE
Can't able to pass DRM token in header in iOS FairPlay

### ISSUE THREAD

**Issue by arunpandiyanp** [bitmovin/bitmovin-player-react-native#119]
Using BitMovin we integrate the video player in the iOS application using react native. Regular video and DRM video also played well in the Application. But I Can't be able to play DRM-protected content (Need to inculdeDRM Token videos) videos not able to play. In other platforms like Web they are passing inside of Fairplay they are passing header for DRM token. in react native i can't able to pass that option.

```
 fairplay: {
          licenseUrl: 'OUR KEY',
          certificateUrl: 'OUR URL',
       licenseRequestHeaders: { 
        'Content-type': 'application/octet-stream',
       'preauthorization': currentProgram?.DRMToken, 
      },
       certificateRequestHeaders: { 
        'Content-type': 'application/octet-stream',
       'preauthorization': currentProgram?.DRMToken, 
      },
}
```

i passed like that also. it's not working. Can you please explain how to pass DRM Token in BitMovin for Fairplay React native iOS

**Comment by rolandkakonyi** [comment]
Hi @arunpandiyanp! Thank you for reaching out!

I have tried and the headers are sent once configured, so it might be a possible misconfiguration on your integration.

Here is a working example with our sample FairPlay stream where headers are sent along with certificate and license requests:
```ts
const source: SourceConfig = {
  url: 'https://fps.ezdrm.com/demo/video/ezdrm.m3u8',
  type: SourceType.HLS,
  drmConfig: {
    fairplay: {
      licenseUrl:
        'https://fps.ezdrm.com/api/licenses/09cc0377-6dd4-40cb-b09d-b582236e70fe',
      certificateUrl: 'https://fps.ezdrm.com/demo/video/eleisure.cer',
      licenseRequestHeaders: {
        'Content-type': 'application/octet-stream',
        'x-custom-data': 'custom data license request header',
      },
      certificateRequestHeaders: {
        'Content-type': 'application/octet-stream',
        'x-custom-data': 'custom data certificate request header',
      },
      prepareMessage: (message, assetId) => {
        return message;
      }
    },
  },
};
```

Please let us know if this resolves your issue!

**Comment by arunpandiyanp** [comment]
Hi @rolandkakonyi  , My actual problem is Using BitMovin normal video and DRM content is working fine. Above you mentioned code i already added it's fine for DRM content. My problem is encrypt DRM content needs header for passing the DRM token. For example  Bitmovin Web platform they config like this 


 ```
fairplay: {
      LA_URL: "LA_URL",
      certificateURL: "My certificate",
      _drmName: 'Fairplay-HTML5',
      headers: {
        'Content-type': 'application/octet-stream',
    'preauthorization': drmToken,
      },
      maxLicenseRequestRetries: 0,
      useUint16InitData: true,
      prepareMessage: (event, session) => event.message,
      prepareContentId: (initData) => {
        const { ContentId, KeyId } = extractHlsHeaderData(initData);
        return {"ContentId": "${ContentId}", "KeyId": "${KeyId}"};
      },
```

In iOS react native i don't have any option to add header like this : 

```
   headers: {
        'Content-type': 'application/octet-stream',
    'preauthorization': drmToken,
      },
```

That's why i can't able to play encrypted DRM content.

**Comment by rolandkakonyi** [comment]
@arunpandiyanp the `headers` property of the Web Player SDK is `licenseRequestHeaders` on the React Native bridge (and on iOS/tvOS), therefore using the same values should be sufficient.

You can find the documentation for the Web Player SDK property [here](https://cdn.bitmovin.com/player/web/8/docs/interfaces/drm.applefairplaydrmconfig.html#headers) and its equivalent on the iOS/tvOS Player SDK [here](https://cdn.bitmovin.com/player/ios/3/docs/Classes/FairplayConfig.html#/c:@M@BitmovinPlayer@objc(cs)BMPFairplayConfig(py)licenseRequestHeaders).

So in your snippet you could replace:
```
      headers: {
        'Content-type': 'application/octet-stream',
        'preauthorization': drmToken,
      },
```

with:
```
      licenseRequestHeaders: {
        'Content-type': 'application/octet-stream',
        'preauthorization': drmToken,
      },
```

If you are looking for using HTTP headers on HLS playlists, that is not yet exposed on this React Native library, but we happily accept contributions.
For HLS segments, there is a technical limitation on Apple platforms which prevents us from customizing segment requests with custom headers.

**Comment by arunpandiyanp** [comment]
@rolandkakonyi  Got it. I will check and let you know. Thank you for your response

**Comment by arunpandiyanp** [comment]
Hi @rolandkakonyi  , I'm getting errors like this 
`{"code": null, "data": {"code": 500, "message": "The operation couldn’t be completed. (com.bitmovin.source.error error 2306.)", "underlyingError": {"code": 2306, "description": "Error Domain=com.bitmovin.source.error Code=2306 \"(null)\"", "domain": "com.bitmovin.source.error", "localizedDescription": "The operation couldn’t be completed. (com.bitmovin.source.error error 2306.)"}}, "message": "DRM license request failed.", "name": "onSourceError", "timestamp": 1684929084.768861}`

i searched your site: https://cdn.bitmovin.com/player/android/3/docs/-player%20-module/com.bitmovin.player.api.deficiency/-source-error-code/index.html can't able to find  **error Code=2306**

**Comment by arunpandiyanp** [comment]
https://github.com/arunpandiyanp/bitmovindemoplayer

**Comment by arjunsj** [comment]
Hi @rolandkakonyi  , do you know why we are getting " DRM license request failed" with Conax DRM. do you have any documents which help us integrating Conax DRM in bitmovin react native app

**Comment by jamesdavidholding** [comment]
Hi @arunpandiyanp  

Bitmovin is in the process of moving all tickets from the React-Native project into Bitmovin's standard support ticketing system. Can you please confirm if you are still having an issue? And if so, re-raise this ticket through your Bitmovin Support ticketing system.

Many thanks,

James

**Comment by arjunsj** [comment]
@jamesdavidholding  Yes, we are still facing the issue. we are yet unable to play conax DRM encrypted content with Bitmovin ReactNative SDK.
