### ISSUE TITLE
Unable to install latest version 0.7.0

### ISSUE THREAD

**Issue by jonathanm-tkf** [bitmovin/bitmovin-player-react-native#140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to install the latest version 0.7.0 and it won't allow me to install it via YARN, or NPM.

`yarn add bitmovin-player-react-native`

### Expected Behavior

Install npm module

### What platform(s) are you experiencing the issue on?

- [ ] Android
- [ ] Android TV / Fire TV
- [ ] iOS
- [ ] tvOS

### Player React Native SDK version

0.7.0

### Additional information / Code snippets / Screenshots

Trace: 
  Invariant Violation: expected hoisted manifest for "bitmovin-player-react-native#react-native#@react-native-community/cli"
      at invariant (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:2314:15)
      at _loop2 (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:94966:9)
      at PackageHoister.init (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:95036:19)
      at PackageLinker.getFlatHoistedTree (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:48744:20)
      at PackageLinker.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:48755:27)
      at Generator.next (<anonymous>)
      at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
      at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:328:14
      at new Promise (<anonymous>)
      at new F (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:5301:28)

**Comment by rolandkakonyi** [comment]
Hi @jonathanm-tkf can you check the proposed solutions from here if any of it helps?
https://github.com/yarnpkg/yarn/issues/7244

I can not reproduce the issue above in a sample React Native project.

**Comment by jonathanm-tkf** [comment]
Hi @rolandkakonyi 

I understand, I have no idea why it works on version 0.6.0 and not on 0.7.0, do you recommend migrating to YARN version 3?

Thanks

**Comment by jonathanm-tkf** [comment]
yarn --version
1.22.10

**Comment by rolandkakonyi** [comment]
@jonathanm-tkf some of the suggestions say either to remove your `yarn.lock` file or to check if you have a pinned `react-native` dependency with an incompatible version with our lib.

**Comment by jonathanm-tkf** [comment]
Thank you very much @rolandkakonyi, I will keep looking into it then, thank you very much for the help.

**Comment by jonathanm-tkf** [comment]
I have removed yarn.lock removed node_modules, try to update yarn and npm, I am using "react-native": "0.67.4", I think the minimum would be 0.64.0

thanks

**Comment by jonathanm-tkf** [comment]
Checking the code I see that they have a dependency on "react-native": "0.69.10", what would be the reason?

**Comment by jonathanm-tkf** [comment]
@rolandkakonyi 

https://github.com/bitmovin/bitmovin-player-react-native/commit/1496ce55f56ba03477544047eb6b4ba235a3575f

Thanks

**Comment by jonathanm-tkf** [comment]
Hi @rolandkakonyi I create a simple repository 0.67.4 if you try to add 

`yarn add bitmovin-player-react-native`

You have the error, I really appreciate your help thanks.

https://github.com/jonathanm-tkf/PlayerTest

**Comment by rolandkakonyi** [comment]
Thanks for the details @jonathanm-tkf, this helps a lot!
We are working on a solution!

**Comment by rolandkakonyi** [comment]
@jonathanm-tkf thank you for the patience!

Here comes the new version which has the fix for this problem:

https://github.com/bitmovin/bitmovin-player-react-native/releases/tag/v0.7.1

Please verify if this resolves the problem for your project!

**Comment by jonathanm-tkf** [comment]
Thanks for your help, I'm checking, thanks again
