### ISSUE TITLE
This is not a bug, it would be more of an implementation query.

### ISSUE THREAD

**Issue by jonathanm-tkf** [bitmovin/bitmovin-player-react-native#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I apologize for not making a functionality request but maybe from my side I can help to implement it, I need some guidance if possible.

I have the following scenario:

I have a service that has a delay time and I need to show a load, seeing that the player has the buffering event, is it possible to somehow send that message to the skin? example I create the player instance I send it the buffering event and once I have everything I need I remove it from buffering mode.

If the scenario is too complex, the other possible solution would be to have the onSourceLoaded event or some other event notify us once the player is loaded + buffered, for example, 10 seconds.

In effect, I am trying to avoid double loading, one by an RN component and the second via the Player. 

Thanks for your help

### Expected Behavior

Change mode loading on player

### What platform(s) are you experiencing the issue on?

- [ ] Android
- [ ] Android TV / Fire TV
- [ ] iOS
- [ ] tvOS

### Player React Native SDK version

I apologise for not making a functionality request but maybe from my side I can help to implement it, I just need some guidance if possible.  I have the following scenario:  I have a service that has a delay time and I need to show a load, seeing that the player has the buffering event, is it possible to somehow send that message to the skin? example I create the player instance I send it the buffering event and once I have everything I need I remove it from buffering mode?  In case the scenario is too complex, the other possible solution would be to have the onSourceLoaded event or some other event to notify us once the player is loaded + buffered, for example 10 seconds.

**Comment by jamesdavidholding** [comment]
Hi @jonathanm-tkf  thanks for the ask, and apologies on no radio silence on this ticket.

So we can discuss this more fully both with support and engineering am I correct to understand that you want to force the buffering  (spinner) to present ahead of the actual source and player intialising? 

Am I understanding the scenario correctly? Is there a reason the request and load take so long that requires this handling?

**Comment by jamesdavidholding** [comment]
Also, I noticed that this ticket has been open for a while, it might be you found a work around to this scenario, in which case it would still be good to hear the case and solution so we can understand the workflow implemented.

Mant thanks 
James

**Comment by rolandkakonyi** [comment]
Hi @jonathanm-tkf!

The scenario you described would most likely need a fork of our open-source [Player UI](https://github.com/bitmovin/bitmovin-player-ui) to implement the external trigger for the loading overlay and use it based on our [guide here](https://developer.bitmovin.com/playback/docs/customizing-the-html-player-ui).

> If the scenario is too complex, the other possible solution would be to have the onSourceLoaded event or some other event notify us once the player is loaded + buffered, for example, 10 seconds.

`onReady` event is the indication that the player is ready for immediate playback, you could use that for your use case to hide your own initial loading overlay in combination with your own loading state.

What do you think about these possible solutions?

**Comment by jamesdavidholding** [comment]
Hi @jonathanm-tkf 

This is just a quick note to confirm whether you received the previous note from our engineers on how this can best be achieved.

Do you have any further questions on this topic we can answer? please let us know.

Best regards,

James

**Comment by jonathanm-tkf** [comment]
Hello, good morning @rolandkakonyi @jamesdavidholding 

Thank you very much for the answer and what a pity not to respond earlier, have been hard weeks in the project for that reason I could not see this issue, indeed we have a fork as @rolandkakonyi  comments and we will try to follow the suggestion, responding a little to @rolandkakonyi  is correct and indeed we have implemented in this way 2 layers one would be the spinner and another would be the player as such, which is quite complicated the synchronization of when to place one and remove the other, I understand that it is something extremely custom, in most cases only my business rules but you are the experts and I wanted some recommendation, thank you very much in the case that you do not come up with any similar solution let's close the case and I will try to take the course from my side.

Thank you and best regards

**Comment by jamesdavidholding** [comment]
thanks @jonathanm-tkf I will therefore close this ticket as you suggest.
