### ISSUE TITLE
[iOS] - Subtitles in Picture in Picture mode

### ISSUE THREAD

**Issue by MateoParodi** [bitmovin/bitmovin-player-react-native#147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Im not able to see the subtitles (.vtt) when in Picture in Picture mode, I also noticied that this happen in the demos of bitmovin.. is there any chance to enable captions on PiP? 

### Expected Behavior

Continuing seeing the subtitles when in PiP

### What platform(s) are you experiencing the issue on?

- [ ] Android
- [ ] Android TV / Fire TV
- [X] iOS
- [ ] tvOS

### Player React Native SDK version

0.6.0

### Device / Environment

- Device - iPhone 12 Prop
- TestFlight

**Comment by bitbalint** [comment]
Hi @MateoParodi ,

Thanks for raising this issue. The feature you described (subtitles in PiP) is not currently available in either our native iOS SDK or the React Native SDK. While this feature isn’t something currently on our roadmap, we’ll be monitoring further interest for this issue and we’ll let you know here when there is any movement.

Regards,
Balint

**Comment by jamesdavidholding** [comment]
Hi @MateoParodi,

This feature suggestion is not currently on the roadmap and has not been suggested by other customers today. 
We recommend raising this suggestion in our Community; other customers can then also vote on this suggestion.

As an open source project we also welcome contributions, details of how to raise feature suggestions and contribute can be found here:

https://developer.bitmovin.com/playback/docs/react-native-introduction#not-seeing-the-features-youre-looking-for

Many thanks 

James
