### ISSUE TITLE
Subtitles on Android appear lower out of frame.

### ISSUE THREAD

**Issue by YoucefBen47** [bitmovin/bitmovin-player-react-native#154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On Android as seen in the attached image the subtitles appear lower than they should be.
I added color red to the subtitle-overlay container.

### Expected Behavior

Subtitles are contained within the subtitle-overlay container.

### What platform(s) are you experiencing the issue on?

- [X] Android
- [ ] Android TV / Fire TV
- [ ] iOS
- [ ] tvOS

### Player React Native SDK version

0.7.2

### Additional information / Code snippets / Screenshots

![Screenshot_2023-07-07-20-26-38-236_com fliikamobilern](https://github.com/bitmovin/bitmovin-player-react-native/assets/70854871/fa8ca134-3d69-4486-b117-a1e7ba66602e)
![Screenshot_2023-07-07-20-26-31-701_com fliikamobilern](https://github.com/bitmovin/bitmovin-player-react-native/assets/70854871/6c85e8e5-3822-4184-9cdb-54aa4dcba316)

**Comment by christophaigner** [comment]
Hi @YoucefBen47,

Thank you for reporting this.
To help us reproduce the issue it would be great if you could share a sample stream (either here or via email to christoph.aigner@bitmovin.com).

Chris

**Comment by YoucefBen47** [comment]
Hi @christophaigner ,
You can see the issue on the example app when playing the SubtitlePlayback screen starting from minute 02:00. If there is one line of subtitles it appears fine. If there is a second line it appears out of frame like you can see in the attached image. in our custom CSS I have made the subtitles-overlay a bit narrower so the subs don't span the entire width of the screen. I also had to lower the subs placement when the seekbar was visible because they were moving up a little bit too high and we added custon play and forward/backward buttons so the subs appear on top of the buttons. As a fix for the subs appearing out of the frame I decreased the height of the subtitles-overlay container. 
![Screenshot_2023-07-13-17-25-20-494_com bitmovin player reactnative example](https://github.com/bitmovin/bitmovin-player-react-native/assets/70854871/967c5e31-ff17-4e52-b4ac-2597beee7b87)

**Comment by christophaigner** [comment]
Hi @YoucefBen47,

Thanks again for reporting and providing more details.
We will look into this.

**Comment by jamesdavidholding** [comment]
Hi @YoucefBen47

We will soon be moving all open and active ssues to Bitmovin Support Dashboard. Please confirm if this is still an issue for you?

Many thanks 

James

**Comment by YoucefBen47** [comment]
Hi @jamesdavidholding,
We use custom CSS to push the subtitles to the top on Android. I uncommented the custom styles and as you can see in the screenshots if there is only one line of subtitles it appears just fine. When the seekbar is there the subtitles are pushed to the top. If there is a second line in the subtitles it appears out of frame.
Thank you.
![Screenshot_2023-10-02-14-16-53-691_com fliikamobilern](https://github.com/bitmovin/bitmovin-player-react-native/assets/70854871/a2e0d19f-9cb8-446b-9eae-fb0492b397d2)
![Screenshot_2023-10-02-14-16-58-008_com fliikamobilern](https://github.com/bitmovin/bitmovin-player-react-native/assets/70854871/c15456db-58ca-44dd-83d1-0b9234042d0b)
![Screenshot_2023-10-02-14-17-17-466_com fliikamobilern](https://github.com/bitmovin/bitmovin-player-react-native/assets/70854871/0f09d32b-0ddb-4878-ac83-ccdcbdf91a65)

**Comment by jamesdavidholding** [comment]
Thanks @YoucefBen47 Support and engineering will review. 
As we will soon be archiving this support tab and moving tickets through to customers' bitmovin dashboard, can you confirm for me your organisation so that if this ticket is still open, we can move it through to the right company and continue working on it with you? 

Many thanks 

James

**Comment by jamesdavidholding** [comment]
@YoucefBen47  Please can provide us with your organisation name or ID so we can port this ticket over to your bitmovin Dashboard. Or alternatively, re-raise this ticket through your Bitmovin support dashboard. 

We will be archiving GH issues at the end of next week and at that point, all open tickets will be moved to customers' bitmovin support dashboard where we can. 


James

**Comment by matamegger** [comment]
A fix for the issue is included in the latest release ([v0.18.0](https://github.com/bitmovin/bitmovin-player-react-native/releases/tag/v0.18.0)). Once you update, there should be no additional configuration needed in regard to this ticket.

(cc @jamesdavidholding)
