### ISSUE TITLE
Build fails during pod install with Expo managed project

### ISSUE THREAD

**Issue by LukyLurks** [bitmovin/bitmovin-player-react-native#158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I created an Expo-managed React Native project and wanted to use the Bitmovin player with it. I [set up the dependencies](https://developer.bitmovin.com/playback/docs/setting-up-your-projects) as per the documentation, using [Expo's mods and config plugins](https://docs.expo.dev/config-plugins/development-and-debugging).

When using [Expo Application Services (EAS)](https://docs.expo.dev/eas/) to build a development app for iOS, the build fails with the following error log:
```
Using Expo modules
[Expo] Enabling modular headers for pod ExpoModulesCore
Auto-generating `.xcode.env.local` with $NODE_BINARY=/Users/expo/.nvm/versions/node/v16.18.1/bin/node
Auto-linking React Native module for target `testingbitmovinonios`: RNBitmovinPlayer
Framework build type is static framework
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
[Codegen] Found FBReactNativeSpec
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Fetching podspec for `hermes-engine` from `../node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec`
Cloning spec repo `bitmovin-cocoapod-specs` from `https://github.com/bitmovin/cocoapod-specs.git`
[!] Unable to find a specification for `libevent (~> 2.1.12)`
You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
pod exited with non-zero code: 1
``` 

### Expected Behavior

I expect the build  to succeed.

### Steps To Reproduce

1. Have an Expo account (prerequisite).
2. Be enrolled in the Apple Developer Program and have an iPhone (prerequisite).
3. Clone [this minimal reproduction repository](https://github.com/LukyLurks/testing-bitmovin-for-ios).
4. Open a terminal at the root of the project directory and run `eas build --platform ios --profile development`.
5. Wait for the build to fail, and consult the logs in your Expo dashboard.

### What platform(s) are you experiencing the issue on?

- [ ] Android
- [ ] Android TV / Fire TV
- [X] iOS
- [ ] tvOS

### Player React Native SDK version

v3.36.0

### Device / Environment

- Build environment: I am using Expo Application Services. I send Expo my project files and they build the project with their own computers.
- The detailed steps of Expo's iOS build process can be found here: https://docs.expo.dev/build-reference/ios-builds/.
- I was not able to find the specifications for the computers they use to run the build. I will update this post and comment about it if I do.
- I'm using bitmovin-player-react-native v0.7.2.

### Additional information / Code snippets / Screenshots

- Android builds succeed. You can test it by following the reproduction steps until 4, where you should run `eas build --platform android --profile development` instead.
- Using EAS doesn't allow me to run `pod repo update` or `pod install --repo-update`, an often suggested fix for the error I'm encountering. Or if it does, I have not yet found how.
- I don't have a computer running macOS to experiment with these commands locally.

**Comment by jonathanm-tkf** [comment]
hi @LukyLurks  I think this project is not supported by Expo, maybe someone from Bitmovin technical team can help you.

**Comment by LukyLurks** [comment]
Thanks to Bitmovin support my issue is solved, I just had to add more sources. In addition to `source 'https://github.com/bitmovin/cocoapod-specs.git'` in my Podfile as per the Bitmovin docs, I was suggested to add `source 'https://github.com/react-native-tvos/react-native-tvos-podspecs.git'` which solves the issue regarding `libevent`. Then I still had to add `source 'https://github.com/CocoaPods/Specs.git'` to fix similar errors that occurred with some other dependencies.

What confuses me is that one of these other dependencies ([react-native-mmkv](https://github.com/mrousavy/react-native-mmkv)) gets installed without issue when I remove bitmovin-player-react-native from my project. But that's not relevant to the issue or to this repository, so I believe I can close this.
