### ISSUE TITLE
Android TV player UI focus issue

### ISSUE THREAD

**Issue by xayoung** [bitmovin/bitmovin-player-react-native#161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

run on Android TV simulator. When I seek the video once, it stays focused on the progress bar.
apple tvOS is work perfect.

### Expected Behavior

When the UI is hidden, the focus is reset. mabe better?

### What platform(s) are you experiencing the issue on?

- [ ] Android
- [X] Android TV / Fire TV
- [ ] iOS
- [ ] tvOS

### Player React Native SDK version

0.7.2

### Device / Environment

System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
    Memory: 81.16 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node

"bitmovin-player-react-native": "^0.7.2",
"expo": "^49.0.3",
"react": "18.2.0",
"react-native": "npm:react-native-tvos@^0.71.10-0"

### Additional information / Code snippets / Screenshots

https://github.com/bitmovin/bitmovin-player-react-native/assets/13132789/c25ecf6f-5548-4951-afdf-5a20147c2bb1

**Comment by christophaigner** [comment]
Hi @xayoung,

Thank you for your feedback & great to see your interest in using Bitmovin on React Native.
We’ll be monitoring further interest on this issue as well as other channels and will let you know here when there is any movement.

Chris

**Comment by jamesdavidholding** [comment]
Hi @xayoung  

Thank you for suggesting this, We have logged it with the product team to take into consideration as they continue to contribute to this project. As an open-source project we also welcome contributions from anyone should you wish to make a contribution please see https://github.com/bitmovin/bitmovin-player-react-native#contributing-to-this-project

For any other suggestions please do raise them in our community forum https://github.com/bitmovin/bitmovin-player-react-native#raising-a-feature-suggestion where others can also add their vote towards them.


Many thanks 
James
