### ISSUE TITLE
Incorrect stylization at Fullscreen

### ISSUE THREAD

**Issue by NazarKuryl0** [bitmovin/bitmovin-player-react-native#166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

@react-navigation is present in almost all React Native projects. When using it, the player goes to full screen with incorrect styling ([image example](https://postimg.cc/YjsCfr8v)). 

The idea of workaround was to use Modal from react-native, but in that case fullscreenHandler is working incorrect: onFullscreenEnter callback works only after the second tap on fullscreen icon, thats why icon didn't change color in first time.

### Expected Behavior

The player must overlap @react-navigation components or if use Modal - onFullscreenEnter callback should work correct

### Steps To Reproduce

1. Init new Ract-Native app by running command `npx react-native@latest init AwesomeProject`
2. add this dependencies into package.json 
`@react-native-community/masked-view`
`@react-navigation/bottom-tabs`
`@react-navigation/native`
`bitmovin-player-react-native`
`react-native-gesture-handler`
`react-native-reanimated`
`react-native-safe-area-context`
`react-native-screens`
3. chane in podfile min_ios_version_supported to '14.0' and add 
`source 'https://github.com/bitmovin/cocoapod-specs.git'`
`source 'https://cdn.cocoapods.org/'`
4. from ios folder run `pod install`
5. change App.jsx to first or second sample and change your licance key and video uri
6. run app, by using command `yarn ios` or `npm run ios`

### What platform(s) are you experiencing the issue on?

- [X] Android
- [ ] Android TV / Fire TV
- [X] iOS
- [ ] tvOS

### Player React Native SDK version

0.7.2

### Sample 1 (with default fullscreen styles):

```
import React, { useEffect, useCallback, useState } from 'react';
import { NavigationContainer } from '@react-navigation/native';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import {
  Dimensions,
  View,
  StyleSheet,
Modal,
} from 'react-native';
import {
  usePlayer,
  SourceType,
  PlayerView,
  FullscreenHandler,
} from 'bitmovin-player-react-native';

const videoUri = 'SOME-VIDEO_URI'
const width = Dimensions.get('screen').width;

class SampleFullscreenHandler implements FullscreenHandler {
  isFullscreenActive: boolean = true;
  onFullscreen: (fullscreenMode: boolean) => void;

  constructor(
    isFullscreenActive: boolean,
    onFullscreen: (fullscreenMode: boolean) => void
  ) {
    this.isFullscreenActive = isFullscreenActive;
    this.onFullscreen = onFullscreen;
  }

  enterFullscreen(): void {
    this.onFullscreen(true);
    this.isFullscreenActive = true;
  }

  exitFullscreen(): void {
    this.onFullscreen(false);
    this.isFullscreenActive = false;
  }
}

const Screen = () => {
  const [fullscreenMode, setFullscreenMode] = useState(false);
  const fullscreenHandler = new SampleFullscreenHandler(
    fullscreenMode,
    setFullscreenMode
  );
  const player = usePlayer({
    licenseKey: 'YOUR-LICENCE_KEY',
  });

  useEffect(() => {
    player.load({
      url: videoUri,
      type: SourceType.HLS,
    });
    return () => {
      player.destroy();
    };
  }, [player]);

  const onReady = useCallback(() => {
    player.play();
  }, [player]);

  return (
    <View style={styles.root}>
      <PlayerView
        style={fullscreenMode ? styles.playerFullscreen : styles.player}
        player={player}
        onReady={onReady}
        fullscreenHandler={fullscreenHandler}
      />
    </View>
  )
}

const Tab = createBottomTabNavigator();

function App() {
  return (
    <NavigationContainer>
      <Tab.Navigator>
        <Tab.Screen
          name="Home"
          component={Screen}
          options={{
            tabBarLabel: 'Home',
          }}
        />
      </Tab.Navigator>
    </NavigationContainer>
  );
}

const styles = StyleSheet.create({
  root: {
    flex: 1,
  },
  player: {
    width,
    height: width * 9 / 16,
  },
  playerFullscreen: {
    flex: 1,
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'black',
  },
});

export default App;

```

### Sample 2 (with Modal)
Change this 
```
return (
    <View style={styles.root}>
      <PlayerView
        style={fullscreenMode ? styles.playerFullscreen : styles.player}
        player={player}
        onReady={onReady}
        fullscreenHandler={fullscreenHandler}
      />
    </View>
  )
```

Into this 
```
const Container = fullscreenMode ? Modal : View;

  return (
    <Container style={styles.root}>
      <PlayerView
        style={fullscreenMode ? styles.playerFullscreen : styles.player}
        player={player}
        onReady={onReady}
        fullscreenHandler={fullscreenHandler}
        onFullscreenEnter={()=>console.log('onFullscreenEnter')}
      />
    </Container>
  )
```

**Comment by rolandkakonyi** [comment]
Hi @NazarKuryl0!

Thank you for your detailed report!

Could you try the following changes?

1. Change `const Screen = () => {` to `const Screen = ({navigation}) => {`
2. Change `fullscreenHandler` initialization to:
```ts
  const fullscreenHandler = new SampleFullscreenHandler(
    fullscreenMode,
    (isFullscreen: boolean) => {
      setFullscreenMode(isFullscreen);
      navigation.setOptions({
        headerShown: !isFullscreen, // show/hide top bar
        tabBarStyle: {display: isFullscreen ? 'none' : 'flex'}, // show/hide bottom bar
      });
    },
  );
```

With the above changes I managed to get the following result:
|Fullscreen|Normal|
|---|---|
|<img width="480" src="https://github.com/bitmovin/bitmovin-player-react-native/assets/2691371/29f12a88-554e-4ca8-afdd-1c61ae75803a"/>|<img width="480" src="https://github.com/bitmovin/bitmovin-player-react-native/assets/2691371/6c7ed261-eb86-43ca-a577-a87fbaad38be"/>|

**Comment by rolandkakonyi** [comment]
In the meantime we updated our guide to implement fullscreen playback, please see here: https://developer.bitmovin.com/playback/docs/enabling-fullscreen-playback

**Comment by rolandkakonyi** [comment]
@NazarKuryl0 Did the above solution proposal help?

**Comment by rolandkakonyi** [comment]
Closing this issue due to already provided workaround.
