### ISSUE TITLE
Is it possible to enter/exit fullscreen mode without pressing on icon in controls?

### ISSUE THREAD

**Issue by NazarKuryl0** [bitmovin/bitmovin-player-react-native#179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Fullscreen handler works ok, just when we pressing on icon in controls

### Expected Behavior

Will be great, if we could enter/exit fullscreen mode when we need that without pressing on icon in controls. For example, when user is pressing back on android device or as its show in sample. If you run app with sample code, you will see, that logs from ```exitFullscreen``` or ```enterFullscreen``` works ok, but from ```onFullscreenEnter={(e)=>console.log(e)}```didn't

### Steps To Reproduce

1. Init new react-native application, by running next command
```npx react-native@latest init AwesomeProject```
2. add bitmovin library, by running one of next commands:
for npm: ```npm install bitmovin-player-react-native --save```
for yarn: ```yarn add bitmovin-player-react-native```
3. chane in podfile min_ios_version_supported to '14.0' and add
```source 'https://github.com/bitmovin/cocoapod-specs.git'```
```source 'https://cdn.cocoapods.org/'```
4. from ios folder run ```pod install```
5. change App.jsx to sample and change your license key and video uri
6. run application, by running ```npm run ios``` or ```yarn ios```

### What platform(s) are you experiencing the issue on?

- [X] Android
- [ ] Android TV / Fire TV
- [X] iOS
- [ ] tvOS

### Player React Native SDK version

0.8.0

### Sample:
```
import React, { useEffect, useCallback, useState } from 'react';
import {
  Dimensions,
  View,
  StyleSheet,
  TouchableOpacity,
} from 'react-native';
import {
  usePlayer,
  SourceType,
  PlayerView,
  FullscreenHandler,
} from 'bitmovin-player-react-native';

class SampleFullscreenHandler implements FullscreenHandler {
  isFullscreenActive: boolean = true;
  onFullscreen: (fullscreenMode: boolean) => void;

  constructor(
    isFullscreenActive: boolean,
    onFullscreen: (fullscreenMode: boolean) => void
  ) {
    this.isFullscreenActive = isFullscreenActive;
    this.onFullscreen = onFullscreen;
  }

  enterFullscreen(): void {
console.log('enterFullscreen')
    this.onFullscreen(true);
    this.isFullscreenActive = true;
  }

  exitFullscreen(): void {
console.log('exitFullscreen')
    this.onFullscreen(false);
    this.isFullscreenActive = false;
  }
}

const videoUri = 'YOUR-VIDEO-URI';
const width = Dimensions.get('screen').width;

const App = () => {
  const player = usePlayer({
    licenseKey: 'YOUR-LICENCE_KEY',
  });

  const [fullscreenMode, setFullscreenMode] = useState(false);
    const fullscreenHandler = new SampleFullscreenHandler(
        fullscreenMode,
        (isFullscreenModeActive: boolean) => {
            setFullscreenMode(isFullscreenModeActive);
          },
    );

  useEffect(() => {
    player.load({
      url: videoUri,
      type: SourceType.HLS,
    });
  }, [player]);

  const onReady = useCallback(() => {
    player.play();
  }, [player]);

  return (
    <View style={styles.root}>
      <PlayerView
        style={styles.player}
        player={player}
        onReady={onReady}
        fullscreenHandler={fullscreenHandler}
        onFullscreenEnter={(e)=>console.log(e)}
      />
      <TouchableOpacity style={{width:50,height:50,backgroundColor:'red'}} onPress={()=>{
        if (fullscreenMode) {
          fullscreenHandler.exitFullscreen();
          setFullscreenMode(false);
        } else {
          fullscreenHandler.enterFullscreen();
          setFullscreenMode(true);
        }
      }}/>
    </View>
  )
}

const styles = StyleSheet.create({
  root: {
    flex: 1,
  },
  player: {
    width,
    height: width * 9 / 16,
  },
});

export default App;
```

**Comment by matamegger** [comment]
Hi @NazarKuryl0, to programmatically request fullscreen you can use the `isFullscreenRequested` property on the `PlayerView`. An example usage of this property can be found in the `LandscapeFullscreenHandling` example screen.

For your sample, if you set the `PlayerView` property like this `isFullscreenRequested={fullscreenMode}`, then there should be no need to call `fullscreenHandler.enter/exitFullscreen` in your button callback. Only `setFullscreenMode(...)`.
Let me know if this resolves your issue or if there are further questions.

**Comment by NazarKuryl0** [comment]
Thanks, it works!
