### ISSUE TITLE
Problem with player, black screen with controls but video don't present

### ISSUE THREAD

**Issue by jonathanm-tkf** [bitmovin/bitmovin-player-react-native#180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello, we have a problem with the player because it loses the video on the screen and only shows the controls, the audio is heard but the image is not represented on the device.

I've created a repository with a branch called "error", and I'll add a video demonstrating the problem.

Apparently, there is a problem with the player instance because the image is not displayed but the audio persists in the app, we have also noticed that the default skin of Bitmovin-player-ui has a double-tap functionality on the screen, which allows you to exit fullscreen mode making the video resize and appear on the screen, it is also in the attached video.

https://github.com/bitmovin/bitmovin-player-react-native/assets/67608970/0d391ffc-abb1-4e82-88b1-e7e1a745af7c

This double tap functionality unfortunately we don't have in our integration which makes it impossible for the user to do any action, The only thing you can do is via the back button and then try again, this is quite frustrating to be honest.

Points to consider

- The playback starts with audio and video, after a few seconds or minutes the playback continues with no video, only audio and the player goes black.

- There is no crash, the UI is still fully interactive, but video is completely gone.

- Scrubbing to an already watched section of the playback doesn't solve the issue, video will not recover in any case.

We know the issue is more prevalent in bad connections and it's device specific and on Android 10 or lower. No prevalence in iOS at all.

In the last 4 months we've had at least 30 clients complaining of the issue explicitly in the play store, a few examples attached:

![image](https://github.com/bitmovin/bitmovin-player-react-native/assets/67608970/e594e4fd-36ec-453e-8435-1f3a48194744)

I also attach a video of when this behaviour works correctly, in some cases and we don't know what the reason is. honestly, it's like flipping a coin and having the probability that it will work or not.

https://github.com/bitmovin/bitmovin-player-react-native/assets/67608970/17f046a4-982c-4bcc-adf5-04f250e974b7

### Expected Behavior

As we see the idea and the expectation is that the user can make use of the player by placing a next episode button, the only thing it does is to load a video, for that we use the ```player.load``` functionality which is provided in the integration. 

### Steps To Reproduce

1 - Download the repository
2 - Run the app locally
3- Clic on Landscape Fullscreen Britbox option
4- We wait for the video to load, we do seek if we prefer it.
5- Click on Next Episode, this will display a react native modal.
6- we place a pin, it is not necessary that it is letters or numbers because it does not fulfil the expected function, it is simply a simulation because we do not know what is the reason of the error.
7- Using the ```player.load``` functionality we load a new video.
8 - The video should be displayed without any problems but it does not

### What platform(s) are you experiencing the issue on?

- [X] Android
- [ ] Android TV / Fire TV
- [ ] iOS
- [ ] tvOS

### Player React Native SDK version

0.8.0

### Device / Environment

Samsung galaxy S20 - Android 10
We suspect that it is not the only device and also that it is not the only version of Android.

We tested this same scenario on the same device but with Android 11, 12, and 13 and it works as it should.

### Stream URL (Optional)

https://bitmovin-a.akamaihd.net/content/MI201109210084_1/mpds/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.mpd, https://bitdash-a.akamaihd.net/content/sintel/sintel.mpd

### Additional information / Code snippets / Screenshots

It seems that if the video somehow expires after a resize, it returns to its normal state.

Attached is the forked repository that we have 

https://github.com/take0ffmedia/BBX-bitmovin-player-RN/tree/error

I also refer to the specific file

https://github.com/take0ffmedia/BBX-bitmovin-player-RN/blob/error/example/src/screens/LandscapeFullscreenHandlingBritbox.tsx

If you need APK the link it's this: https://drive.google.com/file/d/1K0qOGipOFSRNGnQOt_-LWoI3HRABOVcM/view?usp=sharing

Thank you very much

**Comment by christophaigner** [comment]
Hi @jonathanm-tkf,

Thanks very much for putting in the effort to create such an extensive bug report - this is really helpful.
For now, we believe we have enough infos to start investigating further.

We will post an update here as soon as we know more.

Chris

**Comment by christophaigner** [comment]
Hi @AngeloFragliassoBritBox,

Thanks again for sharing this extensive report, we're currently looking into it and will keep you posted as soon as there's an update.

Chris

**Comment by jonathanm-tkf** [comment]
Hi @christophaigner thanks for the update, let me know if you need any help

Thanks again

**Comment by christophaigner** [comment]
Hi @jonathanm-tkf & @AngeloFragliassoBritBox,

We've just released [v0.9.0](https://github.com/bitmovin/bitmovin-player-react-native/releases/tag/v0.9.0), which should fix this issue (see #186 for more details).

Could you please test this again?

Thanks,
Chris

**Comment by jonathanm-tkf** [comment]
Hi guys we have the same error on v.0.9.0

You can see the error on APK

https://drive.google.com/file/d/10dN9BeE2GebnioRbACxcIw-gra8hIaib/view?usp=sharing

![image](https://github.com/bitmovin/bitmovin-player-react-native/assets/67608970/ead26d55-ec94-4a53-b285-f37b95326b7d)

**Comment by jonathanm-tkf** [comment]
Thanks @christophaigner I think it's working thanks for your help
