### ISSUE TITLE
React native android is not showing cast icon feature in the bitmovin player

### ISSUE THREAD

**Issue by iyyappanrock535** [bitmovin/bitmovin-player-react-native#201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

So i'm using bitmovin-player-react-native@0.7.2 this player cast fetaure is working ios but android cast icon is not shwoing.

### Expected Behavior

I want enable cast feature react native android.

### What platform(s) are you experiencing the issue on?

- [X] Android
- [ ] Android TV / Fire TV
- [ ] iOS
- [ ] tvOS

### Player React Native SDK version

0.7.2

### Device

Android

### Environment

react-native:0.72.3

### Additional information / Code snippets / Screenshots

![WhatsApp Image 2023-08-22 at 1 58 02 AM](https://github.com/bitmovin/bitmovin-player-react-native/assets/84359596/248ce0dc-cf1f-4656-ba15-ef447799a17b)

**Comment by christophaigner** [comment]
Hi @iyyappanrock535,

Great to hear your interest in using Bitmovin on React Native, and thanks for your feedback regarding our SDK.
Casting is currently not yet fully supported in this project but is already on our roadmap for later this year (also see the [Features section](https://developer.bitmovin.com/playback/docs/react-native-introduction#features) in our Developer Documentation).

We will post an update here once it's available.

Thanks again,
Chris

**Comment by iyyappan02** [comment]
Okay understood the cast is not currently full support but atleast we need to support little. Why its not showing cast icon in android react native cli?

**Comment by jamesdavidholding** [comment]
Hi @iyyappanrock535 

Casting has now been added to the RN wrapper.

Please see the features section at https://developer.bitmovin.com/playback/docs/react-native-introduction#features
And specific casting guidance at https://developer.bitmovin.com/playback/docs/enabling-google-cast-support

Should you have any other feature suggestions, please check out https://developer.bitmovin.com/playback/docs/react-native-introduction#not-seeing-the-features-youre-looking-for for details of how to contribute or raise a suggestion.

Many thanks,

James
