### ISSUE TITLE
Latest Release 0.9.1 Not Deployable to Apple App Store

### ISSUE THREAD

**Issue by joornby-angel** [bitmovin/bitmovin-player-react-native#203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The latest release includes an update to the BitmovinPlayer dependency to 3.43.0.  In version 3.42.0, the BitmovinPlayerAnalytics vendor framework was introduced with a CFBundleShortVersionString of `3.39.0-a.16`.  The Apple App store requires that short version strings in the bundle "must be a period-separated list of at most three non-negative integers".

### Expected Behavior

For the BitmovinPlayerAnalytics.xcframework to be one of the non-alpha builds of the framework, so that the newest bitmovin player version can be uploaded as an app.

### What platform(s) are you experiencing the issue on?

- [ ] Android
- [ ] Android TV / Fire TV
- [X] iOS
- [X] tvOS

### Player React Native SDK version

0.9.1

**Comment by rolandkakonyi** [comment]
Hi @joornby-angel, thank you for raising this issue!

We confirmed and identified the problem and are working on a solution now.
I will update you once we have the fix available in the coming days.

**Comment by rolandkakonyi** [comment]
Hi @joornby-angel, please verify with our latest release [`v0.9.2`](https://github.com/bitmovin/bitmovin-player-react-native/releases/tag/v0.9.2) if the issue still persists!

**Comment by joornby-angel** [comment]
> Hi @joornby-angel, please verify with our latest release [`v0.9.2`](https://github.com/bitmovin/bitmovin-player-react-native/releases/tag/v0.9.2) if the issue still persists!

Yep, that resolved it.  Thanks!
