### ISSUE TITLE
Live Streaming Mid roll ads positions are not working properly

### ISSUE THREAD

**Issue by arunpandiyanp** [bitmovin/bitmovin-player-react-native#210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
advertisingConfig:{
    schedule: [
      // First ad item at "pre" (default) position.
      {
      position: 'pre',
      sources: [
        {
          tag: adTags.vastSkippable,
          type: AdSourceType.IMA,
        },
      ],
    },
      {
        sources: [
          {              
            type: AdSourceType.IMA,
            tag:adTags.vastSkippable,
          },
        ],
        position: '500.0',

      },
     
    ],
```
 Current behaviour is after playing pre roll ads within the sec mid roll ads are playing when I give whatever position I will give . "500" or "5000". I try to play Live streaming inbetween ads . so I have only option to give fractional sec 

### Expected Behavior

Need to play mid roll ads in 5mins in Live stream 

### Steps To Reproduce

1. First Pre roll ads are played 
2. again Live content need to play 
3. after 5 mins of playing live content again mid roll ads need to be play 

### What platform(s) are you experiencing the issue on?

- [X] Android
- [X] Android TV / Fire TV
- [ ] iOS
- [ ] tvOS

### Player React Native SDK version

0.9.2

**Comment by matamegger** [comment]
Hi @arunpandiyanp, I think the reported behaviour is expected.
The `position` that is configured for ads is a `currentTime` position. For VoD streams the current time usually starts at 0 and ends at the duration time. However, for live streams this is quite different. The `currentTime` for live streams is a timestamp.
e.g. for a DASH live stream at the live edge you get a `currentTime` timestamp that's around the the real time current time timestamp.

I would recommend to use the `Player.scheduleAd` function to dynamically schedule your ads. As `position` you can use the timestamp you want to play the ad e.g. once playback started you can use `currentTime + 500.0` to schedule an ad 500 seconds in the future.
You can also use the `Player.scheduleAd` function to schedule an ad for now, just use `currentTime` as the position then.

Let us know if this resolves your issue, or if we can provide further guidance!

**Comment by arunpandiyanp** [comment]
Hi @matamegger  , we tried using currentTime timestamp. it's not working properly . after pre ads completed mid ads are playing .

**Comment by matamegger** [comment]
For some HLS live streams, the `currentTime` will be not equal to the unix timestamp. However, the important value is still the `currentTime` as the underlying property is also used to trigger ad playback.

Just to clarify, you are seeing a `currentTime` that is equal to or greater than the time you scheduled the ad, but the ad does not start playback?

**Comment by arunpandiyanp** [comment]
HI @matamegger  , we tried with basic ads example and it's not working and we are giving unix timestamp and greater value than current time

**Comment by jamesdavidholding** [comment]
Hi @arunpandiyanp could I request you raise this issue through the bitmovin support dashboard under your Main company organisation? The support team will, with assistance from the engineering team, attempt to replicate your issue.

As part of your ticket your example player config, and a test stream we can assist in replicating this with you. 

If you can also provide the Bitmovin Support ticket ID to this thread that would also be most helpful.

Many thanks 
 
James

**Comment by jamesdavidholding** [comment]
Hi @arunpandiyanp, 

Apologies I just re-read the thread and noticed you stated this is reproducible in the basic ads example. 

We will create an investigation ticket for this PRN-47

As we will be sunsetting the GitHub issues in the not-too-distant future would you be able to email me your organisation and bitmovin username so I can ensure this ticket gets moved to your company's support dashboard?

Many thanks 

James

**Comment by arunpandiyanp** [comment]
Hi @jamesdavidholding We are also facing "General error occurred" issues in player most of the times. This we are encountering while streaming live content.

**Comment by jamesdavidholding** [comment]
Hi @arunpandiyanp

As this is a duplicate ticket of #631 let's continue the discussion in 631. As this support tab will soon be archived.

For any new questions, like the one raised above please creat a separate new ticket within your customer repo.

Many thanks 

James
