### ISSUE TITLE
PlayerView not loaded on tvOS 16.4

### ISSUE THREAD

**Issue by eugenepranoto** [bitmovin/bitmovin-player-react-native#221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am currently trying to run a basic PlayerView in my React Native app, and it's not displaying anything on the screen. The sound of the video is playing, but there is no video content visible.

my code

```ts
export default function Video({ url, thumbnail, title }: IVideoProps) {
  const player = new Player();
  const onReady = useCallback(
    (event: any) => {
      console.log("ready")
      // Start playback
      player.play();
      console.log(event.timestamp);
    },
    [player]
  );
  useFocusEffect(
    useCallback(() => {
      console.log("load video")
      player.load({
        url: !checkIsAndroid()
          ? "https://bitmovin-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8"
          : "https://bitmovin-a.akamaihd.net/content/MI201109210084_1/mpds/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.mpd",
        type: !checkIsAndroid() ? SourceType.HLS : SourceType.DASH,
        title: "Art of Motion",
        poster:
          "https://bitmovin-a.akamaihd.net/content/MI201109210084_1/poster.jpg",
        thumbnailTrack:
          "https://cdn.bitmovin.com/content/assets/art-of-motion-dash-hls-progressive/thumbnails/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.vtt",
      });
      return () => {
        player.destroy();
      };
    }, [player])
  );
 return <View style={styles.flex1}>
 <PlayerView style={styles.flex1} player={player} onReady={onReady} />
</View>
}
```

### Expected Behavior

The video player is showing like in android tv emulator

### What platform(s) are you experiencing the issue on?

- [ ] Android
- [ ] Android TV / Fire TV
- [ ] iOS
- [X] tvOS

### Player React Native SDK version

^0.9.2

### Environment

```
"react": "18.2.0",
"react-native": "npm:react-native-tvos@0.71.12-0",
```

### Stream URL (Optional)

-

### Additional information / Code snippets / Screenshots

-

**Comment by rolandkakonyi** [comment]
Hi @eugenepranoto!

Thank you for taking the time to report this issue. The team will investigate it further and keep you updated.

In the spirit of open-source collaboration, please also consider [contributing](https://github.com/bitmovin/bitmovin-player-react-native/blob/development/CONTRIBUTING.md) a fix - your first-hand experience with the issue would be invaluable for improving the SDK.

Thanks again,
Bitmovin team

**Comment by rolandkakonyi** [comment]
@eugenepranoto are you running on tvOS simulator or real tvOS device?
If you are running on the tvOS simulator, it is a known issue that video is rendered black in the iOS 16 and tvOS 16 simulators.

Possible workarounds are:
- Use a real tvOS device
- Use tvOS 17 simulator

Please confirm if this was helpful for you!

**Comment by eugenepranoto** [comment]
I see thank you for the insight. @rolandkakonyi 

I have more question

- When I try to concentrate on the player progress, I find myself unable to navigate to other sections like the settings or audio icons. When I press the left/right or top/down buttons, it only results in the player seeking forward or backward by approximately 5 seconds. Is there a way to improve navigation within the player interface?
- Can I customize the position of the settings icon to appear on top of the player progress bar instead of being displayed in the top-right corner?
- Is it possible to change the behavior of the settings popup from being a modal window to appearing as a sidebar on the right side of the interface?

**Comment by rolandkakonyi** [comment]
Hi @eugenepranoto!

> * When i first load the video. Im unable to start the video using controller gesture. i need to press the player directly using my mouse to play it

What do you mean by mouse? Are you testing on the tvOS simulator?
In that case you need to select the simulator window to control the simulator with your keyboard - if you mean that as controller gesture.
The virtual on-screen Apple TV remote control also works. I just tried it.

> * When I try to concentrate on the player progress, I find myself unable to navigate to other sections like the settings or audio icons. When I press the left/right or top/down buttons, it only results in the player seeking forward or backward by approximately 5 seconds. Is there a way to improve navigation within the player interface? maybe the seeking only work when i press left/right?

Pressing left/right when the seek bar is selected is works as expected by seeking backward/forward.
Using top/down results in moving to the other UI elements, like subtitles or audio options when using our example application from this repository.

> * Can I customize the position of the settings icon to appear on top of the player progress bar instead of being displayed in the top-right corner?

No, this UI Apple's built-in vide player UI that comes with the given tvOS version.
You can implement your own UI by disabling our UI using `usePlayer({ styleConfig: { isUiEnabled: false }})` and overlaying your own UI on top of `<PlayerView .../>`

> * Is it possible to change the behavior of the settings popup from being a modal window to appearing as a sidebar on the right side of the interface?

No, the same applies here as for the previous question. You have to build your own solution for this.


I hope this helps!

If you have further requests, feel free to raise a support ticket, as described in detail [here](https://github.com/bitmovin/bitmovin-player-react-native/issues/273).
