### ISSUE TITLE
Add styleConfig using a url localhost

### ISSUE THREAD

**Issue by JoseGuerreroT** [bitmovin/bitmovin-player-react-native#228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, I'm trying to add styleConfig custom using a localhost url like this: 
 

```
  usePlayer({
    url: 'https://bitmovin-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8',
    type: Platform.OS === 'ios' ? SourceType.HLS : SourceType.DASH,
    title: 'Art of Motion',
    styleConfig: {
      playerUiCss:
        'http://localhost:8886/ancillary/ancillary-8124A9FA-00B0-4A1C-A406-EC82D104BC96.css?uuid=8124A9FA-00B0-4A1C-A406-EC82D104BC96',
      playerUiJs:
        'http://localhost:8886/ancillary/ancillary-D482A5FD-76B0-4075-8FAF-E889EA6E7D70.js?uuid=D482A5FD-76B0-4075-8FAF-E889EA6E7D70',
    },
  });
```
However, such styles are not loaded by the player.
Player controls are disabled and no iteration is allowed. Here I show you:

https://github.com/bitmovin/bitmovin-player-react-native/assets/14618190/4caec393-7f20-40fa-9bf4-00dd1802b297

I loaded the aforementioned localhost URLs (css and js) into a webview, and as we can see they load without problems:

<img width="375" alt="image" src="https://github.com/bitmovin/bitmovin-player-react-native/assets/14618190/821e19e3-7803-4d24-afd6-c9b61663a4e7">

```
    <SafeAreaView style={{ flex: 1 }}>
      <Text style={{ color: 'white' }}>WebView For CSS File</Text>
      <WebView
        source={{
          uri: "http://localhost:8595/ancillary/ancillary-8124A9FA-00B0-4A1C-A406-EC82D104BC96.css?uuid=8124A9FA-00B0-4A1C-A406-EC82D104BC96"
        }}
        style={{ flex: 1 }}
      />
      <Text style={{ color: 'white' }}>WebView For JS File</Text>
      <WebView
        source={{
          uri: "http://localhost:8595/ancillary/ancillary-D482A5FD-76B0-4075-8FAF-E889EA6E7D70.js?uuid=D482A5FD-76B0-4075-8FAF-E889EA6E7D70"
        }}
        style={{ flex: 1 }}
      />
    </SafeAreaView>
```

if you can guide me on how to solve this problem I would appreciate it,  thank you very much.

### Expected Behavior

The URLs are expected to load just as if we were using remote URLs, like this:

https://github.com/bitmovin/bitmovin-player-react-native/assets/14618190/542abec2-db42-445e-98f7-2b94929756ec

### What platform(s) are you experiencing the issue on?

- [ ] Android
- [ ] Android TV / Fire TV
- [X] iOS
- [ ] tvOS

### Player React Native SDK version

0.9.2

### Device

iPhone 12 - iOS 14.2

### Environment

- React version: 18.2.0
- React native version: 0.72.4
- Node Version: v16.20
- Xcode version: 14.3

### Stream URL (Optional)

https://bitmovin-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8

**Comment by coloradude** [comment]
Hi @JoseGuerreroT, would you please try using 127.0.0.1 instead of localhost and see if this resolves the issue?

**Comment by JoseGuerreroT** [comment]
I've tried that, and it doesn't work. @coloradude  Thank you very much for your reply.

**Comment by jonathanm-tkf** [comment]
Hi @coloradude any suggestion on this issue?

Thanks

**Comment by rolandkakonyi** [comment]
Hi @JoseGuerreroT!

Could you try adding this to your `Info.plist`?

```
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
```

Please note that this might only work when running the simulator as when running on a real iOS device, localhost will be the iOS device.

Another option, in case you use this `localhost` hosted content for development, please consider exposing it via `ngrok` or similar solution.

**Comment by jamesdavidholding** [comment]
Hi Jose,

Since we haven’t heard back from you on this ticket after a few reminders, we will automatically close it for now. If this topic is still relevant to you, please feel free to raise a new ticket through your bitmovin support dashboard, where we’ll be glad to continue assisting you.

Please note the issues tab of this repository is being retired at the end of this month, this will enable customers to raise tickets more swiftly and directly to customer support.

Best regards,

James
