### ISSUE TITLE
Client-side Ads API

### ISSUE THREAD

**Issue by pogist** [bitmovin/bitmovin-player-react-native#24]
Client-side ads should be configurable via `PlayerConfig.advertisingConfig` during the player's creation:

```typescript
export const MyPlayer = () => {
  const player = usePlayer({
    // Player license key
    licenseKey: '...',
    // Ads configuration
    advertisingConfig: {
      schedule: [
        {
          // This object represents an AdItem
          position: "pre",
          sources: [
            {
              tag: 'ad-url',
              type: AdSourceType.IMA,
            },
            {
              tag: 'ad-url-fallback1',
              type: AdSourceType.IMA,
            },
            {
              tag: 'ad-url-fallback2',
              type: AdSourceType.IMA,
            },
            /* fallbacks... */
          ],
        },
        {
          position: "20%",
          sources: [
            {
              tag: 'ad-url',
              type: AdSourceType.IMA,
            },
            /* fallbacks... */
          ],
        },
        /* other ad items... */
      ],
    },
  });

  // Player methods related to Ads
  useEffect(() => {
    // Check whether an ad is playing right now.
    player.isAd().then((isAd) => {
      // `isAd` = true when an ad is being played.
    });

    // Skips the current ad. Has no effect if ad is not skippable or if no ad is played back.
    player.skipAd();

    // Schedules an ad for playback.
    player.scheduleAd({
      position: "post",
      sources: [
        {
          tag: 'ad-url',
          type: AdSourceType.IMA
        },
        {
          tag: 'ad-url-fallback',
          type: AdSourceType.IMA
        },
        /* more fallbacks... */
      ],
    });
  });

  return (
    <PlayerView
      player={player}
      onAdBreakStarted={/* ... */}
      onAdBreakFinished={/* ... */}
      onAdClicked={/* ... */}
      onAdSkipped={/* ... */}
      onAdError={/* ... */}
      {/* other event listeners... */}
    />
  );
};
```

And in order to support this, a bunch of native types must be bridged (or at least type-anotated)
on the JavaScript level. This way, I reached out to both native docs and came up with the
following definitions for a possible JavaScript ads API.

Note this only serves to give an idea of how the JavaScript API should look like and what native types
should be bridged instead of going into implementation details. 

All presented types and properties are intended to be common between Android and iOS.

### Type definitions

- `AdvertisingConfig` ([android](https://cdn.bitmovin.com/player/android/3/docs/-player%20-module/com.bitmovin.player.api.advertising/-advertising-config/index.html) | [ios](https://cdn.bitmovin.com/player/ios/3/docs/Classes/BMPAdvertisingConfig.html))
```typescript
interface AdvertisingConfig {
  schedule: AdItem[];
}
```
- `AdItem` ([android](https://cdn.bitmovin.com/player/android/3/docs/-player%20-module/com.bitmovin.player.api.advertising/-ad-item/index.html) | [ios](https://cdn.bitmovin.com/player/ios/3/docs/Classes/BMPAdItem.html))
```typescript
interface AdItem {
  position?: string;
  sources: AdSource[];
}
```
- `AdSource` ([android](https://cdn.bitmovin.com/player/android/3/docs/-player%20-module/com.bitmovin.player.api.advertising/-ad-source/index.html) | [ios](https://cdn.bitmovin.com/player/ios/3/docs/Classes/BMPAdSource.html))
```typescript
interface AdSource {
  tag: string;
  type: AdSourceType;
}
```
- `AdSourceType` ([android](https://cdn.bitmovin.com/player/android/3/docs/-player%20-module/com.bitmovin.player.api.advertising/-ad-source-type/index.html) | [ios](https://cdn.bitmovin.com/player/ios/3/docs/Enums/BMPAdSourceType.html))
```typescript
enum AdSourceType {
  IMA,
  UNKNOWN,
  PROGRESSIVE,
}
```
- `AdConfig` ([android](https://cdn.bitmovin.com/player/android/3/docs/-player%20-module/com.bitmovin.player.api.advertising/-ad-config/index.html) | [ios](https://cdn.bitmovin.com/player/ios/3/docs/Protocols/BMPAdConfig.html))
```typescript
interface AdConfig {
  replaceContentDuration: number;
}
```
- `AdQuartile` ([android](https://cdn.bitmovin.com/player/android/3/docs/-player%20-module/com.bitmovin.player.api.advertising/-ad-quartile/index.html) | [ios](https://cdn.bitmovin.com/player/ios/3/docs/Enums/BMPAdQuartile.html))
```typescript
enum AdQuartile {
  FIRST,
  MID_POINT,
  THIRD,
}
```
- `AdBreak` ([android](https://cdn.bitmovin.com/player/android/3/docs/-player%20-module/com.bitmovin.player.api.advertising/-ad-break/index.html) | [ios](https://cdn.bitmovin.com/player/ios/3/docs/Protocols/BMPAdBreak.html))
```typescript
interface AdBreak {
  ads: Ad[];
  id: string;
  scheduleTime: number;
}
```
- `Ad` ([android](https://cdn.bitmovin.com/player/android/3/docs/-player%20-module/com.bitmovin.player.api.advertising/-ad/index.html) | [ios](https://cdn.bitmovin.com/player/ios/3/docs/Protocols/BMPAd.html))
```typescript
interface Ad {
  clickThroughUrl?: string;
  data?: AdData;
  height: number;
  id?: string;
  isLinear: boolean;
  mediaFileUrl?: string;
  width: number;
}
```
- `AdData` ([android](https://cdn.bitmovin.com/player/android/3/docs/-player%20-module/com.bitmovin.player.api.advertising/-ad-data/index.html) | [ios](https://cdn.bitmovin.com/player/ios/3/docs/Protocols/BMPAdData.html))
```typescript
interface AdData {
  bitrate?: number;
  maxBitrate?: number;
  mimeType?: string;
  minBitrate?: number;
}
```
- `AdBreakStartedEvent` ([android](https://cdn.bitmovin.com/player/android/3/docs/-player%20-module/com.bitmovin.player.api.event/-player-event/-ad-break-started/index.html) | [ios](https://cdn.bitmovin.com/player/ios/3/docs/Classes/AdBreakStartedEvent.html))
```typescript
interface AdBreakStartedEvent extends Event {
  adBreak?: AdBreak;
}
```
- `AdBreakFinishedEvent` ([android](https://cdn.bitmovin.com/player/android/3/docs/-player%20-module/com.bitmovin.player.api.event/-player-event/-ad-break-finished/index.html) | [ios](https://cdn.bitmovin.com/player/ios/3/docs/Classes/AdBreakFinishedEvent.html))
```typescript
interface AdBreakFinishedEvent extends Event {
  adBreak?: AdBreak;
}
```
- `AdStartedEvent` ([android](https://cdn.bitmovin.com/player/android/3/docs/-player%20-module/com.bitmovin.player.api.event/-player-event/-ad-started/index.html) | [ios](https://cdn.bitmovin.com/player/ios/3/docs/Classes/AdStartedEvent.html))
```typescript
interface AdStartedEvent extends Event {
  clickThroughUrl?: string;
  clientType?: AdSourceType;
  duration: number;
  indexInQueue: number;
  position?: string;
  skipOffset: number;
  timeOffset: number;
  ad?: Ad;
}
```
- `AdFinishedEvent` ([android](https://cdn.bitmovin.com/player/android/3/docs/-player%20-module/com.bitmovin.player.api.event/-player-event/-ad-finished/index.html) | [ios](https://cdn.bitmovin.com/player/ios/3/docs/Classes/AdFinishedEvent.html))
```typescript
interface AdFinishedEvent extends Event {
   ad?: Ad;
}
```
- `AdErrorEvent` ([android](https://cdn.bitmovin.com/player/android/3/docs/-player%20-module/com.bitmovin.player.api.event/-player-event/-ad-error/index.html) | [ios](https://cdn.bitmovin.com/player/ios/3/docs/Classes/AdErrorEvent.html))
```typescript
interface AdErrorEvent extends ErrorEvent {
  adConfig?: AdConfig?
  adItem?: AdItem;
}
```
- `AdClickedEvent` ([android](https://cdn.bitmovin.com/player/android/3/docs/-player%20-module/com.bitmovin.player.api.event/-player-event/-ad-clicked/index.html) | [ios](https://cdn.bitmovin.com/player/ios/3/docs/Classes/AdClickedEvent.html))
```typescript
interface AdClickedEvent extends Event {
  clickThroughUrl?: string;
}
```
- `AdSkippedEvent` ([android](https://cdn.bitmovin.com/player/android/3/docs/-player%20-module/com.bitmovin.player.api.event/-player-event/-ad-skipped/index.html) | [ios](https://cdn.bitmovin.com/player/ios/3/docs/Classes/AdSkippedEvent.html))
```typescript
interface AdSkippedEvent extends Event {
   ad?: Ad;
}
```
- `AdQuartileEvent` ([android](https://cdn.bitmovin.com/player/android/3/docs/-player%20-module/com.bitmovin.player.api.event/-player-event/-ad-quartile/index.html) | [ios](https://cdn.bitmovin.com/player/ios/3/docs/Classes/AdQuartileEvent.html))
```typescript
interface AdQuartileEvent extends Event {
  quartile: AdQuartile;
}
```
- `AdScheduledEvent` ([android](https://cdn.bitmovin.com/player/android/3/docs/-player%20-module/com.bitmovin.player.api.event/-player-event/-ad-scheduled/index.html) | [ios](https://cdn.bitmovin.com/player/ios/3/docs/Classes/AdScheduledEvent.html))
```typescript
interface AdScheduledEvent extends Event {
  numberOfAds: number;
}
```
- `AdManifestLoadEvent` ([android](https://cdn.bitmovin.com/player/android/3/docs/-player%20-module/com.bitmovin.player.api.event/-player-event/-ad-manifest-load/index.html) | [ios](https://cdn.bitmovin.com/player/ios/3/docs/Classes/AdManifestLoadEvent.html))
```typescript
interface AdManifestLoadEvent extends Event {
  adBreak?: AdBreak;
  adConfig?: AdConfig;
}
```
- `AdManifestLoadedEvent` ([android](https://cdn.bitmovin.com/player/android/3/docs/-player%20-module/com.bitmovin.player.api.event/-player-event/-ad-manifest-loaded/index.html) | [ios](https://cdn.bitmovin.com/player/ios/3/docs/Classes/AdManifestLoadedEvent.html))
```typescript
interface AdManifestLoadedEvent extends Event {
  adBreak?: AdBreak;
  adConfig?: AdConfig;
  downloadTime: number;
}
```

**Comment by joornby-angel** [comment]
@pogist What's the status of this issue?  I will have capacity and interest in working on this in the next month.

**Comment by pogist** [comment]
Hi @joornby-angel, I'm currently working on it but thanks a lot for your interest! You can view the progress in the [`feat/advertising`](https://github.com/bitmovin/bitmovin-player-react-native/tree/feat/advertising) branch 😁. Also feel free to give suggestions during the review process once the PR gets opened.

**Comment by joornby-angel** [comment]
@pogist sounds good.  My company has interest in getting this out pretty quickly.  I saw the original plan for release was late 2022 / early 2023.  If that's still the release plan, is there anyway an extra set of hands could expedite the implementation?
