### ISSUE TITLE
[iOS] Player is not playing sound

### ISSUE THREAD

**Issue by donnes** [bitmovin/bitmovin-player-react-native#26]
Hey guys!

I'm integrating the player into a project I'm working on, but I noticed that the player is not playing sound on iOS.

Here's a demo running on an iPhone 13 Pro:

https://user-images.githubusercontent.com/9506146/194437867-3b73914f-e8da-4daa-9f0f-08d564d8dd3c.mp4

**Comment by rolandkakonyi** [comment]
Hey, @donnes! Do you have the ringer switch (the mute switch on the left side) in muted (red) position?
In that case audio will not play by default unless the "Audio, AirPlay, and Picture in Picture" mode is enabled in "Background Modes" capability.

**Comment by donnes** [comment]
Hi @rolandkakonyi! I completely forgot about that switch (mine is always off). Actually with it turned on the audio is playing correctly.

But let me ask, there's a way to play the audio even with the switch off?

**Comment by donnes** [comment]
> @donnes yes, enable background playback for the example app via adding the "Audio, AirPlay, and Picture in Picture" mode is enabled in "Background Modes" capability for the target (on Signing and Capabilities tab).

It's already enabled but the audio is only playing with the switch on

**Comment by pogist** [comment]
Hi, @donnes. Actually, you'll also have to enable background playback on the player configuration besides the `Background Modes` capability. This option is [already available](https://cdn.bitmovin.com/player/ios/3/docs/Classes/PlaybackConfig.html#/c:@M@BitmovinPlayer@objc(cs)BMPPlaybackConfig(py)isBackgroundPlaybackEnabled) on the native iOS SDK, but not on the React Native bridge yet. Though, we're currently working on it and it should be released very soon once we get  [this PR](https://github.com/bitmovin/bitmovin-player-react-native/pull/10) merged.

Basically, once the PR mentioned above gets merged, you'll be able to set the background playback option via `playbackConfig`:

```typescript
const player = usePlayer({
  /* ... */
  playbackConfig: {
    isBackgroundPlaybackEnabled: true, // Enables background playback on iOS
  },
});
```

Unfortunately, there's no other way to set/override this configuration on the current state of the library except by manually editing the native files on your side (which is really cumbersome) and I strongly discourage it.

But no worries, I'll ping you again on this thread once custom playback gets released and hopefully guide you on how to use it if necessary. So stay tuned! 😁

**Comment by donnes** [comment]
@rolandkakonyi @pogist

It's really great to know!

Thanks a lot guys for your support! I'll stay tuned, and probably I'll try to contribute to the library as soon as I get familiar with it. You will see me around 😄

**Comment by rolandkakonyi** [comment]
Sorry @donnes for the incomplete instructions, I misremembered about the default value of that flag.
