### ISSUE TITLE
Issue with Analytics

### ISSUE THREAD

**Issue by jonathanm-tkf** [bitmovin/bitmovin-player-react-native#260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello everyone we have a bug with the implementation of analytics which is of some concern.

We are currently using version 0.9.1, following the official documentation. 

[https://developer.bitmovin.com/playback/docs/enabling-bitmovin-analytics](https://developer.bitmovin.com/playback/docs/enabling-bitmovin-analytics)

Once the player is initialized, we need to send some information 

```typescript
player.analyticsCollector.setCustomDataOnce({
    customData1: `${segment}`,
    customData2: videoData.customId,
    customData3: videoData.supplier,
    customData4: `${t('version')}: ${version} ${t('build')} ${buildNumber}`,
});
```
This data is sent the first time it is displayed on the network.

![image](https://github.com/bitmovin/bitmovin-player-react-native/assets/67608970/6cee3d66-ceef-4eab-badd-210ffc52cb16)

But then a few seconds later another request is sent, which does not have this data, so we assume that the previous request is overwritten.

![image](https://github.com/bitmovin/bitmovin-player-react-native/assets/67608970/3be0b7e9-55bc-4a0e-9f45-4b473d3be019)

Why is this happening?

### Expected Behavior

Get customData properties on each analytics request

### What platform(s) are you experiencing the issue on?

- [X] Android
- [ ] Android TV / Fire TV
- [ ] iOS
- [ ] tvOS

### Player React Native SDK version

0.9.1

**Comment by rolandkakonyi** [comment]
Hi @jonathanm-tkf!

`.setCustomDataOnce()` sends the data only **once**, but does not keep these changes for further requests.
Please use `.setCustomData()` instead!

Thank you for pointing out the error in the documentation, this will be fixed soon!

**Comment by rolandkakonyi** [comment]
Documentation was updated [here](https://developer.bitmovin.com/playback/docs/enabling-bitmovin-analytics).
