### ISSUE TITLE
Unable to find a specification for `GoogleAds-IMA-iOS-SDK (= 3.18.4)` depended upon by `RNBitmovinPlayer`

### ISSUE THREAD

**Issue by IamMasterWayne** [bitmovin/bitmovin-player-react-native#268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to find a specification for `GoogleAds-IMA-iOS-SDK (= 3.18.4)` depended upon by `RNBitmovinPlayer`

### Expected Behavior

Install pods for RNBitmovinPlayer

### Steps To Reproduce

yarn add bitmovin-player-react-native

cd ios

**# Bitmovin pods source url
source 'https://github.com/bitmovin/cocoapod-specs.git'**

### What platform(s) are you experiencing the issue on?

- [ ] Android
- [ ] Android TV / Fire TV
- [x] iOS
- [ ] tvOS

### Player React Native SDK version

0.64.0

### Device

IOS

### Environment

"react": "17.0.1",
"react-native": "0.64.0",
IOS: '14.0'

### Additional information / Code snippets / Screenshots

<img width="564" alt="Screenshot 2023-09-26 at 11 34 46 AM" src="https://github.com/bitmovin/bitmovin-player-react-native/assets/37474482/b7713350-e13a-4520-b01a-81f3df9af5e7">

**Comment by jamesdavidholding** [comment]
Hi @IamMasterWayne 

Just a quick note to confirm whether you received our previous reply and did this resolve your issue?

Best regards,
James

**Comment by jamesdavidholding** [comment]
Hi @IamMasterWayne  Since we have not heard back from you on this question we will close this out and assume our guidance has resolved your issue. if you are still having issues please do raise a ticket through you Bitmovin support Dashboard
