### ISSUE TITLE
Offline playback with bitmovin

### ISSUE THREAD

**Issue by Harry-Anthony** [bitmovin/bitmovin-player-react-native#30]
One of the challenges of enabling offline playback is downloading and managing assets. Is it possible to find this functionality on this package like android and ios using offlineContentManager

**Comment by bitbalint** [comment]
Hi @Harry-Anthony ! 
The offline playback feature (as known from our native SDKs) is not on our React Native roadmap for 2022, and we currently cannot provide an ETA for this feature - we will keep this issue updated.
Thank you
