### ISSUE TITLE
Version issue for analytics 

### ISSUE THREAD

**Issue by ankit-wow** [bitmovin/bitmovin-player-react-native#31]
existing URL added in code when run on browser it return xml.

**Comment by bitbalint** [comment]
Hi @ankit-wow ,
thanks for taking the time to report this issue - could you please provide more detail as to what exactly you are trying to achieve?
You mention 'when run on browser' - this React Native library is intended for iOS/Android native environments and NOT for targeting browsers (see [Device Compatibility](https://github.com/bitmovin/bitmovin-player-react-native#platform-support)).
Please let us know how we can help you further.

**Comment by dweinber** [comment]
Closing due to now feedback.
