### ISSUE TITLE
Player is not working properly on IOS and Android version greater than 10

### ISSUE THREAD

**Issue by vishnushelar** [bitmovin/bitmovin-player-react-native#34]
"bitmovin-player-react-native" is not wot working properly on IOS and Android version greater than 10.
You have any updates on this ?

**Comment by bitbalint** [comment]
Hi @vishnushelar ,
the library has been tested on the iOS 12.4+ and Android 4.1+, see [Platform Support](https://github.com/bitmovin/bitmovin-player-react-native#platform-support).
Could you please provide more detail on the error(s) you are seeing?
I also suggest you try building/exploring the [Example Apps](https://github.com/bitmovin/bitmovin-player-react-native/tree/main/example) provided in the repository - do you also run into issues building these?
Thanks

**Comment by dweinber** [comment]
Closing due to no feedback.
