### ISSUE TITLE
How to use bitmovin analytics in  bitmovin-player-react-native

### ISSUE THREAD

**Issue by vishnushelar** [bitmovin/bitmovin-player-react-native#35]
Hi,

We wanted to use bitmovin analytics in bitmovin-player-react-native. How to use it ?
Do you have code snippets of this ?

**Comment by bitbalint** [comment]
Dear @vishnushelar ,
a React Native library for our Analytics product is in the works, coming early 2023.
Thanks

**Comment by vishnushelar** [comment]
Okay
Thanks for the updates.
