### ISSUE TITLE
Seeking to end of seek bar causing multiple icons (play/pause/loading) to appear.

### ISSUE THREAD

**Issue by backtoyoujames** [bitmovin/bitmovin-player-react-native#51]
When a user slides the seek handle to the end of the seek bar, the player sends a ‘onPlaybackFInished’ event to our event handler.  The finished video event is also sent event when the user is whipping the seek cursor back and forth and happens to hit the far right hand side.  The video stops playing but multiple player controls then appear in the center of the screen.

The reason for the various artifacts is that the seek bar value is higher than the duration of the actual video length in seconds.  e.g. 1120 coming from the seek bar but the duration is 1116.

Shorter videos work as expected because the seek bar is in sync with the duration.  It appears that depending on the video length, the seek bar value can get out of sync with the actual duration over time.

The player seek bar maximum value emitted should never exceed the duration length.

**Comment by rolandkakonyi** [comment]
Hi @backtoyoujames!

Could you provide some more details about this behavior you observed?
Like:
- platform (Android, Android TV, iOS, tvOS)
- the used `bitmovin-player-react-native` version

Can you provide some reproduction steps with a stream that can be used?

The observed behavior sounds familiar which can happen when the indicated total duration in an HLS manifest and the actual sum of segment durations are inconsistent in a stream.

**Comment by jamesdavidholding** [comment]
Hi @backtoyoujames  

Since we have not heard back from you in a while on this ticket, we will close it for now. If you want to reopen it, please can I ask you to raise it through your Bitmovin Support Dashboard, where our support team will be able to follow up with you.

Many thanks 

James
