### ISSUE TITLE
NativePlayerView was not found in the UIManager

### ISSUE THREAD

**Issue by danielgsaavedra** [bitmovin/bitmovin-player-react-native#70]
Hello everyone, I am trying to implement the player but after instantiating it and loading the source I am getting the following error: "Invariant Violation: requiresNativeComponent: 'NativePlayerView' was not found in the UIManager", and I have not been able to find a solution, yes Does anyone know how or have any ideas why this happens? I appreciate the help.
![Captura de pantalla de 2022-12-27 18-35-35](https://user-images.githubusercontent.com/55241451/209724579-75d1c470-e2e9-44bd-b6e4-2376d7540764.png)

**Comment by dweinber** [comment]
There is further discussion in https://community.bitmovin.com/t/nativeplayerview-was-not-found-in-the-uimanager/1598.

**Comment by ggchicote** [comment]
@danielgsaavedra did you find any solution? I'm facing the same problem!

**Comment by dweinber** [comment]
It seems @danielgsaavedra uses the renative framework - are you using that as well @ggchicote?

**Comment by ggchicote** [comment]
No, I'm using a **Bare project** within **Expo**. When I run the following command ```expo starts``` and I try to open de Android emulator it shows the mentioned error.

Is it possible to handle the plugin through a Expo Bare project?

**Comment by dweinber** [comment]
Thanks, interesting. Haven't tried that but I'd assume it should work. I'm just trying to find what could cause this as we haven't seen this with other customer projects, so far we're only aware of your two cases (with Renative and Expo Bare)

**Comment by davidwinograd1** [comment]
Was there any solution to this? @dweinber @danielgsaavedra @ggchicote

**Comment by mahmudsg** [comment]
Was there any solution to this? I'm getting the same!

**Comment by christophaigner** [comment]
Hi all,

Thank you very much for reporting this.
As discussed [here](https://community.bitmovin.com/t/nativeplayerview-was-not-found-in-the-uimanager/1598/2), we would need more details on your environment & setup to be able to investigate further.

Also, we've introduced a new issue template for bugs to make it easier to collect all this information easily and we kindly ask you to **create a new issue with more details** [here](https://github.com/bitmovin/bitmovin-player-react-native/issues/new/choose). Ideally, you could also share a sample project where this is reproducible.

Thank you in advance,
Chris

**Comment by jmvillagra** [comment]
Same here, we're also facing the problem with a brand new project.
The only difference against the examples is that we use react-native-tvOS 0.71.12-0.
