### ISSUE TITLE
FullscreenHandler Interface is not added in export list. Unable to implement the same.

### ISSUE THREAD

**Issue by ravindran-a** [bitmovin/bitmovin-player-react-native#75]
Please add FullscreenHandler interface to the export list in index so that we can implement the same in the projects we are integrating it.
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/19164536/212879065-56166bf2-549d-4445-9a29-d248c7a1fc08.png">

**Comment by rolandkakonyi** [comment]
@ravindran-a Thanks for raising this issue! The fix for this is part of the latest `0.5.1` release.
