### ISSUE TITLE
React Native Bitmovin Google Chrome Casting?

### ISSUE THREAD

**Issue by bll-prataps** [bitmovin/bitmovin-player-react-native#81]
is there any way we can enable bitmovin google chrome casting or it is in development?

**Comment by dweinber** [comment]
Hi @bll-prataps,
This is not yet supported (see also https://github.com/bitmovin/bitmovin-player-react-native#feature-support). This isn't currently being worked on within Bitmovin. 
We'd be happy to take contributions, otherwise we'll let you know when this becomes available.

**Comment by jamesdavidholding** [comment]
Hi @bll-prataps  

Casting has now been added to the RN wrapper. 

Please see the features section at https://developer.bitmovin.com/playback/docs/react-native-introduction#features

Should you have any other feature suggestions, please check out https://developer.bitmovin.com/playback/docs/react-native-introduction#not-seeing-the-features-youre-looking-for for details of how to contribute or raise a suggestion.

Many thanks,
 
James

**Comment by jamesdavidholding** [comment]
Hi @

**Comment by jamesdavidholding** [comment]
Hi @bll-prataps  
Hot off the press - Please find here a link to the related casting documentation  https://developer.bitmovin.com/playback/docs/enabling-google-cast-support
