### ISSUE TITLE
Change color from blue to green

### ISSUE THREAD

**Issue by KiranBluelabel** [bitmovin/bitmovin-player-react-native#83]
Is there any way to turn the video player styles green instead of blue?

**Comment by dweinber** [comment]
This can be done by overriding CSS rules. Add them all to a single CSS file and load it via `supplementalPlayerUiCss` (see https://github.com/bitmovin/bitmovin-player-react-native#customize-html-ui-android-and-ios-only for details).

You can find details on CSS classes in https://bitmovin.com/docs/player/articles/player-ui-css-class-reference or directly in https://github.com/bitmovin/bitmovin-player-ui
