### ISSUE TITLE
Add support for playback configuration

### ISSUE THREAD

**Issue by jonathanm-tkf** [bitmovin/bitmovin-player-react-native#9]
### Description

Possibility to add custom properties to the playback such as isAutoplayEnabled, this would be a perfect way to autoPlay the video once it is loaded, without the need to handle event ``` player.play();```

### Implementation possibility

At the start of initialization, we are using react hook

```
  const player = usePlayer(
    {
      licenseKey: 'LICENCE_KEY',
    },
    {
      isAutoplayEnabled: true, // possibility to add more funcionalities startOffset, etc
    }
  );
```

### Possible validation 

![2022-07-18_14-49-30 (1)](https://user-images.githubusercontent.com/67608970/179599080-a9368432-d12b-4f7d-a797-e00332f09c43.gif)

### Questions

- When implementing the solution in some cases in android we have the following detail, regarding the buffering? which occurs in a non-constant way, only happens on android as it works perfectly well on ios.

![screen-20220718-150418 (3)](https://user-images.githubusercontent.com/67608970/179600098-f4de8696-60e5-44a4-9630-45e39e084d8f.gif)

![2022-07-18_15-11-24](https://user-images.githubusercontent.com/67608970/179599685-f9656a3a-8d2c-4476-8c18-43368b23aaa5.png)

I look forward to possible comments and/or suggestions, and I am happy to help in any way I can, thanks for the effort

Best

**Comment by jonathanm-tkf** [comment]
Hi @pogist 

We can close this isse?

**Comment by pogist** [comment]
@jonathanm-tkf Sure, I'll close it now. Also thanks a lot for your contribution, it is remarkable 🙏
